# Main Dockerfile for creating Metabolic in a container
#
# Metabolic source: https://github.com/AnantharamanLab/METABOLIC
# Dockerfile github: https://github.com/tin6150/metabolic/blob/master/Dockerfile.base
#


#FROM cgrlab/sambamba
#FROM conda/miniconda3  # Debian, not ubuntu, can't find R!
#FROM ubuntu:19.04
FROM r-base:3.6.2
MAINTAINER Tin (at) LBL.gov

#RUN  echo "Building ... this isn't likely working yet" 

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=PST8PDT

RUN touch    _TOP_DIR_OF_CONTAINER_  ;\
    echo "begining docker build process at " | tee -a _TOP_DIR_OF_CONTAINER_  ;\
    export TZ=PST8PDT                                     ;\
    date | TZ=PST8PDT tee -a       _TOP_DIR_OF_CONTAINER_ ;\
    apt-get -y --force-yes --quiet install git wget gzip apt-utils ;\
    test -d /opt/gitrepo  || mkdir -p /opt/gitrepo        ;\
    test -d /opt/gitrepo/metabolic  || git clone https://github.com/tin6150/metabolic.git  ;\
    cd /opt/gitrepo/metabolic &&  git pull && cd -                                         ;\
    echo "installing packages via apt"       | tee -a _TOP_DIR_OF_CONTAINER_               ;\
    apt-get update ;\
    apt-get -y --force-yes --quiet install perl-base r-base hmmer prodigal bamtools python file bash tcsh zsh less vim bc tmux screen xterm xpdf ;\
    apt-get -y --force-yes --quiet install libxml2 libtinfo5 libtinfo6 diamond-aligner     ;\
    apt-get -y --force-yes --quiet install environment-modules libterm-shellui-perl cpanoutdated    ;\
    apt-get -y --force-yes --quiet install libcurl4-openssl-dev libxml2-dev libssl-dev httrack libhttrack-dev libhttrack2 harvest-tools  ;\
    cd /usr/bin && ln -s diamond-aligner diamond && cd - ;\
    dpkg --list > dpkg--list.output ;\
    # libtinfo5,6 added to see if rid of:
    # /usr/lib/R/bin/exec/R: /opt/conda/lib/libtinfo.so.6: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.8)

    echo '==================================================================' ;\
    echo "installing packages cran packages" | tee -a _TOP_DIR_OF_CONTAINER_  ;\
    date | TZ=PST8PDT tee -a      _TOP_DIR_OF_CONTAINER_                      ;\
    echo '==================================================================' ;\
    Rscript --quiet -e 'install.packages("diagram",    repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("forcats",    repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("digest",     repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("htmltools",  repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("rmarkdown",  repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("reprex",     repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("tidyverse",  repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("stringi",    repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("ggthemes",   repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("ggalluvial", repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("reshape2",   repos = "http://cran.us.r-project.org")'    ;\
    Rscript --quiet -e 'install.packages("ggraph",     repos = "http://cran.us.r-project.org")'    ;\
    echo $? > Rscript.exit.code   ;\
    Rscript --quiet -e 'library()' > R_library_list.txt    ;\

    echo 'last line of RUN block in Dockerbuild without continuation :)'

RUN     cd / \
  && touch _TOP_DIR_OF_CONTAINER_  \
  && TZ=PST8PDT date  >> _TOP_DIR_OF_CONTAINER_  \
  && echo  "Dockerfile.base 2019.1225.1222"         >> _TOP_DIR_OF_CONTAINER_   \
  && echo  "Dockerfile.base 2020.0107.1248 (.deb for tidyverse )"  >> _TOP_DIR_OF_CONTAINER_   \
  && echo  "Dockerfile.base 2020.0107.1302 (R_library_list.txt )"  >> _TOP_DIR_OF_CONTAINER_   \
  && echo  "Grand Finale"

# ENV TZ America/Los_Angeles 
# best to leave user choose Time Zone
ENV DOCKERFILE Dockerfile.base 
ENV TEST_DOCKER_ENV     this_env_will_be_avail_when_container_is_run_or_exec
ENV TEST_DOCKER_ENV_REF https://vsupalov.com/docker-arg-env-variable-guide/#setting-env-values
ENV DOCKER_MANTABOLIC_BASE  "Dockerfile.base mostly R/CRAN"
# but how to append, eg add to PATH?

ENTRYPOINT [ "/bin/bash" ]
#ENTRYPOINT [ "TZ=PST8PDT /bin/bash" ]
# if no defined ENTRYPOINT, default to bash inside the container
# can also run with exec bash to get shell:
# docker exec -it tin6150/os4metabolic -v $HOME:/home/tin  bash 
# careful not to cover /home/username (for this container)
